// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using NUnit.Framework;
using UnityEngine;
using System.Collections;

public class ClientServerConnectionTest 
{
	public ClientServerConnectionTest ()
	{
		
	}
	
	public ClientNetwork client;
	public GameObject networkClientSphere;

	
	// NOTE: for this test to pass the server project, and server within it, must be started.
	[Test]
	public void ClientServerConnectionTestMethod ()
	{
		networkClientSphere = new GameObject ();
		networkClientSphere.AddComponent<ClientNetwork> ();
		client = networkClientSphere.GetComponent<ClientNetwork> ();
		//networkClientSphere = GameObject.Find("Sphere").GetComponent<NetworkView>().isc
		//client = GameObject.Find("WhateverObjectHasWeaponSlotsOnIt").GetComponent<ClientNetwork>();


		networkClientSphere.AddComponent<NetworkView>();
		networkClientSphere.SetActive ();
		//int id = networkClientSphere.networkView.GetInstanceID ();
		//networkClientSphere.networkView.observed = this;
		//networkClientSphere.networkView.stateSynchronization = NetworkStateSynchronization.ReliableDeltaCompressed;
		//networkClientSphere.networkView.viewID = Network.AllocateViewID();

		
		//this.client.GetComponent<ClientNetwork> ().ConnectToServer ();
		client.ConnectToServer ();
//		client.


		delay (15);
		Assert.True (client.isConnectedToServer == true);
		
	}
	
	public static void delay (int seconds)
	{
		TimeSpan ts = new TimeSpan(DateTime.Now.Ticks) + TimeSpan.FromSeconds (seconds);
		TimeSpan now;
		do {
			now = new TimeSpan(DateTime.Now.Ticks);
		} while ( now < ts );
	}
	
}


